import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { ApolloProvider } from "@/components/apollo-provider";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";

import "./globals.css";
import { Header } from "../components/header";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Rick And Morty Explorer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "bg-background font-sans antialiased overflow-hidden",
          fontSans.variable
        )}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          <Header />
          <main className="flex h-screen flex-col items-center justify-between p-24">
            <ApolloProvider>{children}</ApolloProvider>
            <div className="text-sm italic">Footer TM</div>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
