import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { Suspense } from "react";

import { ApolloProvider } from "@/components/apollo-provider";
import { Header } from "@/components/header";
import { ThemeProvider } from "@/components/theme-provider";
import { Spinner } from "@/components/ui/spinner";
import { cn } from "@/lib/utils";

import "./globals.css";
import { ErrorBoundary } from "next/dist/client/components/error-boundary";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Rick And Morty Explorer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "overflow-hidden bg-background font-sans antialiased",
          fontSans.variable
        )}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          <Header />
          <main className="flex h-screen flex-col items-center justify-between p-24">
            <Suspense fallback={<Spinner />}>
              <ErrorBoundary
                errorComponent={async (error) => {
                  "use server";
                  return (
                    <div className="text-center text-xl text-destructive">
                      Error fallback: {error.error.message}
                    </div>
                  );
                }}>
                <ApolloProvider>{children}</ApolloProvider>
                <div className="text-sm italic">Footer TM</div>
              </ErrorBoundary>
            </Suspense>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
